# Projects configuration
projects:
  - name: "mHEV"
    start_date: "2025-01-06"
    end_date: "2025-12-15"
    freeze_date: "2025-10-20"
    
  - name: "HEV"
    start_date: "2025-03-10"
    end_date: "2025-11-30"
    freeze_date: "2025-09-15"
    
  - name: "pHEV"
    start_date: "2025-02-15"
    end_date: "2025-10-31"
    freeze_date: "2025-08-25"
    
  - name: "MQB27"
    start_date: "2025-04-01"
    end_date: "2025-12-20"
    freeze_date: "2025-10-10"
    
  - name: "PL PK"
    start_date: "2025-05-12"
    end_date: "2026-01-15"
    freeze_date: "2025-11-20"

# Configuration Change Requests
change_requests:
  - title: "Update CAN matrix"
    body: "Add new CAN nodes for hybrid functionality"
    state: "open"
    project: "mHEV"
    created: "2025-03-15"
    
  - title: "Adjust torque parameters"
    body: "Optimize torque delivery for electric motor"
    state: "in_progress"
    project: "pHEV"
    created: "2025-04-02"
    
  - title: "Implement energy recovery"
    body: "Add configuration for regenerative braking system"
    state: "integrated"
    project: "HEV"
    created: "2025-02-20"
    
  - title: "Update infotainment settings"
    body: "Add new display modes for hybrid systems"
    state: "open"
    project: "MQB27"
    created: "2025-05-10"
    
  - title: "Battery management calibration"
    body: "Optimize charging parameters for new battery chemistry"
    state: "in_progress"
    project: "PL PK"
    created: "2025-06-18"
    
  - title: "Thermal management update"
    body: "Adjust cooling thresholds for electric components"
    state: "integrated"
    project: "mHEV"
    created: "2025-03-28"

# Project filter options
project_filters: ["mHEV", "HEV", "pHEV", "MQB27", "PL PK"]

# Background text
background_text: "Success in configuration management comes from attention to detail, clear communication, and consistent processes. Each change you integrate brings us closer to more reliable and efficient systems."
