common_config_version: 2.4.0
projects:
- name: mHEV
  start_date: '2025-07-04'
  end_date: '2025-10-17'
  freeze_date: '2025-09-05'
  commonconfig: 'false'
- name: MQB27
  start_date: '2025-05-16'
  end_date: '2025-08-15'
  freeze_date: '2025-07-18'
  commonconfig: 'false'
- name: pHEV
  start_date: '2025-05-14'
  end_date: '2025-08-27'
  freeze_date: '2025-07-16'
  commonconfig: 'false'
- name: CC2.4.0
  start_date: '2025-05-21'
  end_date: '2025-07-16'
  freeze_date: '2025-07-11'
  commonconfig: 'true'
change_requests:
- title: RQONE04617456
  body: "[BCC : IoSrv]  - MG1CS311 DMA load Calculation - Config Removal -\ [Test intergrated] SDOM: CC : CONFIG / RQONE04617456_IOSRV_MG1CS311_DMA; 0"
  project: CC2.4.0
  state: in_progress
  created: '2025-07-09'
- title: RQONE04617836
  body: "[BCC : IoExtDev]  - Konfig \xC4nderung zur Korrektur der DGDI-s Feedback-Signale\
    \ (Busy-Signale der beiden DGDI-s) - Funktion Konfig \xC4nderung aus FCC-AR :\
    \ rba_IoExtFscInjS / 1.31.0_CS311_COMMON_BSW2403_C01; 0  \xFCbernehmen"
  project: CC2.4.0
  state: in_progress
  created: '2025-07-09'
- title: RQONE04617193
  body: '[BCC : BswLib] - Enabling NoC Error Logger Register Access Without Debugger
    Connection via HOST_DEBUG_EN Software Workaround'
  project: mHEV
  state: in_progress
  created: '2025-07-09'
- title: RQONE04661229
  body: '[BCC : EbOS] - Correction of ISR Call for Shutdown Task Scheduling in EbOs.
    Take Over BCC : EbOs / 14.12.0_CS311_COMMON_3.2.1; 0 - Test intergrated in CC : CONFIG / RQONE04661229_EBOS_ISR_CORR; 0'
  project: CC2.4.0
  state: in_progress
  created: '2025-07-09'
- title: RQONE04630550
  body: '[BCC : ESM]  - [Common Config 2.4.0] BCC Analysis and Creation : ESM (SWSRC:
    EcuM_Callout_Stubs / 4.16.0_P282.0.0_G00; 1). Take over from SWSRC : EcuM_Callout_Stubs
    / 4.16.0_P282.0.0_G00; 0 - Test integrated in CC : CONFIG / RQONE04630550_ESM_SIL_CHANGES; 0'
  project: CC2.4.0
  state: in_progress
  created: '2025-07-09'
- title: RQONE04637578
  body: ' BCC Analysis and Creation : Changes from  P2444 line'
  project: pHEV
  state: in_progress
  created: '2025-07-10'
- title: RQONE04477120
  body: '[BCC : IoExtDev ???] [IoExtFscDosVlv] and [IoExtFscHlfBr] Perl to java migration
    to support BCT for AR4.5'
  project: CC2.4.0
  state: in_progress
  created: '2025-07-10'
- title: RQONE04651180
  body: '[BCC : SrvLibs] [ST5_28nm Projects] Update BC : SrvLibs to BSW2504'
  project: mHEV
  state: open
  created: '2025-07-10'
- title: RQONE04667930
  body: '[Common Config 2.4.0] BCC Analysis and Creation : PVER : DMG1311VH4C1996
    / N26K10 - RQONE04253582'
  project: HEV
  state: open
  created: '2025-07-10'
- title: RQONE04666209
  body: '[BCC : BswLib, Rte, EbOs] [Common Config 2.4.0] BCC  Analysis and Creation
    :  BswLib, Rte, EbOs'
  project: mHEV
  state: in_progress
  created: '2025-07-10'
project_filters:
- mHEV
- pHEV
- MQB27
- HEV
- CC2.4.0
background_text: CommonConfig delivers fast - high prio requests 1-2 days, standard
  in 2-3 days. We'll even testintegrate it and support as well.
