common_config_version: 2.4.0
projects:
- name: mHEV
  start_date: '2025-07-04'
  end_date: '2025-10-17'
  freeze_date: '2025-09-05'
  commonconfig: 'false'
- name: MQB27
  start_date: '2025-05-16'
  end_date: '2025-08-15'
  freeze_date: '2025-07-18'
  commonconfig: 'false'
- name: pHEV
  start_date: '2025-05-14'
  end_date: '2025-08-27'
  freeze_date: '2025-07-16'
  commonconfig: 'false'
- name: CommonConfig 2.4.0
  start_date: '2025-05-21'
  end_date: '2025-07-16'
  freeze_date: '2025-07-14'
  commonconfig: 'true'
change_requests:
- title: RQONE04617456 - MG1CS311 DMA load Calculation - Config Removal
  body: '[BCC : IoSrv]'
  project: CommonConfig 2.4.0
  state: in_progress
  created: '2025-07-09'
- title: "RQONE04617836 - Konfig \xC4nderung zur Korrektur der DGDI-s Feedback-Signale\
    \ (Busy-Signale der beiden DGDI-s) - Funktion"
  body: "[BCC : IoExtDev] Konfig \xC4nderung aus FCC-AR : rba_IoExtFscInjS / 1.31.0_CS311_COMMON_BSW2403_C01;\
    \ 0  \xFCbernehmen"
  project: CommonConfig 2.4.0
  state: in_progress
  created: '2025-07-09'
- title: RQONE04617193 - Enabling NoC Error Logger Register Access Without Debugger
    Connection via HOST_DEBUG_EN Software Workaround
  body: '[BCC : BswLib] The key register writes are:'
  project: mHEV
  state: in_progress
  created: '2025-07-09'
- title: RQONE04661229 - Correction of ISR Call for Shutdown Task Scheduling in EbOs
  body: '[BCC : EbOS] Take Over BCC : EbOs / 14.12.0_CS311_COMMON_3.2.1; 0'
  project: CommonConfig 2.4.0
  state: in_progress
  created: '2025-07-09'
- title: 'RQONE04630550 - [Common Config 2.4.0] BCC Analysis and Creation : ESM (SWSRC
    : EcuM_Callout_Stubs / 4.16.0_P282.0.0_G00; 1)'
  body: '[BCC : ESM] Take over from SWSRC : EcuM_Callout_Stubs / 4.16.0_P282.0.0_G00;
    0'
  project: CommonConfig 2.4.0
  state: in_progress
  created: '2025-07-09'
- title: 'RQONE04666209 - [Common Config 2.4.0] BCC  Analysis and Creation :  BswLib,
    Rte, EbOs'
  body: '[BCC : BswLib, Rte, EbOs]'
  project: mHEV
  state: in_progress
  created: '2025-07-09'
project_filters:
- mHEV
- pHEV
- MQB27
- HEV
- CommonConfig 2.4.0
background_text: CommonConfig delivers fast - high prio requests 1-2 days, standard
  in 2-3 days. We'll even testintegrate it and support as well.
